//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toujarDataAccess1
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        public long idPhone { get; set; }
        public string marque { get; set; }
        public Nullable<int> memoire { get; set; }
        public Nullable<int> camera { get; set; }
        public string coulleur { get; set; }
        public string isDuos { get; set; }
        public string isNeuf { get; set; }
        public Nullable<long> prix { get; set; }
        public string ville { get; set; }
        public string email { get; set; }
        public string phone1 { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public string image4 { get; set; }
        public string model { get; set; }
        public string trader_name { get; set; }
        public string trader_facebook { get; set; }
        public string trader_insta { get; set; }
        public Nullable<System.DateTime> temps { get; set; }
        public Nullable<int> img_count { get; set; }
        public string password { get; set; }
    }
}
